// api/orders.ts
import api from './index';
import type { Order, PaginatedResponse } from '../types';

/**
 * Payload for creating an order.
 * Mirrors the Django OrderSerializer write fields:
 *   - customer_id   (int, required)
 *   - distributor_id (int | null, optional)
 *   - shipping_address (object, required)
 *   - notes (string, optional)
 *   - items_data: [{ product, quantity, price?, bv? }]  (required, min 1)
 *   - order_number (string, optional — auto-generated by backend if omitted)
 */
export interface OrderCreatePayload {
  customer_id: number;
  distributor_id?: number | null;
  shipping_address: {
    street: string;
    city: string;
    region: string;
    country: string;
    zipCode: string;
  };
  notes?: string;
  order_number?: string;
  items_data: {
    product: number;
    quantity: number;
    price?: number;
    bv?: number;
  }[];
}

/**
 * Payload for updating an order (PUT / PATCH).
 * All fields optional since PATCH is partial.
 */
export type OrderUpdatePayload = Partial<OrderCreatePayload>;

export const orderAPI = {
  // ---------------- GET /orders/ ----------------
  // Returns a paginated list of orders.
  getAll: async (params?: {
    status?: string;
    payment_status?: string;
    [key: string]: any;
  }): Promise<PaginatedResponse<Order>> => {
    try {
      const response = await api.get('/orders/', { params });
      const data = response as any;

      // Backend already returns { count, results } — pass through
      if (data && typeof data === 'object' && Array.isArray(data.results)) {
        return data;
      }

      // If the backend ever returns a bare array, normalize it
      if (Array.isArray(data)) {
        return {
          count: data.length,
          next: null,
          previous: null,
          results: data,
        };
      }

      return {
        count: 0,
        next: null,
        previous: null,
        results: [],
      };
    } catch (error) {
      console.error('Error in orderAPI.getAll:', error);
      throw error;
    }
  },

  // ---------------- GET /orders/<id>/ ----------------
  getById: async (id: number): Promise<Order> => {
    const response = await api.get(`/orders/${id}/`);
    return response as any;
  },

  // ---------------- POST /orders/ ----------------
  // Note: no /create/ suffix — your urls.py routes to the list-create view at the root.
  create: async (data: OrderCreatePayload): Promise<Order> => {
    const response = await api.post('/orders/', data);
    return response as any;
  },

  // ---------------- PATCH /orders/<id>/ ----------------
  // Full/partial update (uses the same OrderSerializer).
  update: async (id: number, data: OrderUpdatePayload): Promise<Order> => {
    const response = await api.patch(`/orders/${id}/`, data);
    return response as any;
  },

  // ---------------- PUT /orders/<id>/ ----------------
  // Full replace (rarely used, kept for completeness).
  replace: async (id: number, data: OrderCreatePayload): Promise<Order> => {
    const response = await api.put(`/orders/${id}/`, data);
    return response as any;
  },

  // ---------------- PATCH /orders/<id>/status/ ----------------
  // Quick status / payment_status update.
  updateStatus: async (
    id: number,
    statusOrPayload: string | { status?: string; payment_status?: string }
  ): Promise<Order> => {
    const body =
      typeof statusOrPayload === 'string'
        ? { status: statusOrPayload.toLowerCase() }
        : {
            ...(statusOrPayload.status && {
              status: statusOrPayload.status.toLowerCase(),
            }),
            ...(statusOrPayload.payment_status && {
              payment_status: statusOrPayload.payment_status.toLowerCase(),
            }),
          };

    const response = await api.patch(`/orders/${id}/status/`, body);
    return response as any;
  },

  // ---------------- DELETE /orders/<id>/ ----------------
  delete: async (id: number): Promise<void> => {
    await api.delete(`/orders/${id}/`);
  },
};